version: '3.1'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    ports:
      - "8000:8000"

  frontend:
    build:
      dockerfile: Dockerfile
      context: "./frontend"
    ports:
      - "5173:5173"