[tool.poetry]
name = "klusteri-website"
version = "0.1.0"
description = ""
authors = ["Laura Peltonen <laura.ms.peltonen@helsinki.fi>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
