FROM python:3.10.13-bullseye

ENV POETRY_VIRTUALENVS_IN_PROJECT=true

WORKDIR /backend

COPY . .

RUN chmod -R 777 *

RUN pip install poetry

RUN poetry config virtualenvs.create false

RUN poetry install --without dev --no-root

EXPOSE 8000

CMD ["/bin/bash", "-c", "python manage.py makemigrations;python manage.py migrate;gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 120 --reload"]
