[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Lotta Tanner <lotta.tanner@helsinki.fi>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^5.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
