# Generated by Django 5.0.1 on 2026-02-02 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=100, unique=True)),
                ('telegram', models.CharField(blank=True, default='', max_length=100)),
                ('role', models.IntegerField(default=5)),
                ('rights_for_reservation', models.BooleanField(default=False)),
                ('first_login', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CleaningSupplies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tool', models.CharField(default='', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefectFault',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=300)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.DateTimeField(blank=True, null=True)),
                ('repaired', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('email', models.EmailField(default='', max_length=100, unique=True)),
                ('homepage', models.CharField(default='', max_length=100)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NightResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_for', models.CharField(default='', max_length=500)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(auto_now=True)),
                ('present', models.BooleanField(default=True)),
                ('late', models.BooleanField(default=False)),
                ('created_by', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organizations', models.ManyToManyField(to='ilotalo.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True)),
                ('end', models.DateTimeField(blank=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('responsible', models.CharField(default='', max_length=100)),
                ('open', models.BooleanField(default=True)),
                ('room', models.CharField(default='', max_length=50)),
                ('created_by', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ilotalo.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('week', models.IntegerField(default=0)),
                ('big', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='big_orgs', to='ilotalo.organization')),
                ('small', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='small_orgs', to='ilotalo.organization')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='keys',
            field=models.ManyToManyField(to='ilotalo.organization'),
        ),
    ]
