# Generated by Django 5.0.1 on 2026-02-06 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0002_alter_event_end_alter_event_room_alter_event_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='big',
            field=models.ForeignKey(db_column='big', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='big_orgs', to='ilotalo.organization'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='small',
            field=models.ForeignKey(db_column='small', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='small_orgs', to='ilotalo.organization'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(db_column='organizer', default=0, on_delete=django.db.models.deletion.CASCADE, to='ilotalo.organization'),
        ),
        migrations.AlterField(
            model_name='nightresponsibility',
            name='user',
            field=models.ForeignKey(db_column='user', default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
