# Generated by Django 5.0.1 on 2024-01-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0002_remove_user_email_remove_user_telegram_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(default='', max_length=100),
        ),
    ]
