# Generated by Django 5.0.1 on 2026-02-07 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0003_alter_cleaning_big_alter_cleaning_small_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='big',
            field=models.ForeignKey(db_column='big', on_delete=django.db.models.deletion.CASCADE, related_name='big_orgs', to='ilotalo.organization'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='small',
            field=models.ForeignKey(db_column='small', on_delete=django.db.models.deletion.CASCADE, related_name='small_orgs', to='ilotalo.organization'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(db_column='organizer', on_delete=django.db.models.deletion.CASCADE, to='ilotalo.organization'),
        ),
        migrations.AlterField(
            model_name='nightresponsibility',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
