# Generated by Django 5.0.1 on 2026-02-08 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0004_event_user_set_null_no_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightresponsibility',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='night_responsibilities_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
