# Generated by Django 5.0.1 on 2024-02-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0005_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
