# Generated by Django 5.0.1 on 2026-02-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0005_alter_nightresponsibility_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightresponsibility',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
