# Generated by Django 5.0.1 on 2024-02-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0009_remove_user_role_remove_user_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
