# Generated by Django 5.0.1 on 2024-02-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0011_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(default='Moi', max_length=100, unique=True),
        ),
    ]
