# Generated by Django 5.0.1 on 2024-02-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0014_alter_user_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True),
        ),
    ]
