# Generated by Django 5.0.1 on 2024-03-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0018_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(default='', max_length=50)),
                ('reservation', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=500)),
                ('responsible', models.CharField(default='', max_length=100)),
                ('open', models.BooleanField(default=True)),
            ],
        ),
    ]
