# Generated by Django 5.0.1 on 2024-03-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0019_alter_user_password'),
        ('ilotalo', '0020_event_end_event_start'),
    ]

    operations = [
    ]
