# Generated by Django 5.0.1 on 2024-03-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0020_event_end_event_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='YKV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=150)),
                ('responsible_for', models.CharField(default='', max_length=500)),
                ('login_time', models.DateTimeField(blank=True, default='1970-01-01 12:00:00')),
                ('logout_time', models.DateTimeField(blank=True, default='1970-01-02 14:00:00')),
                ('present', models.BooleanField(default=True)),
                ('late', models.BooleanField(default=False)),
            ],
        ),
    ]
