# Generated by Django 5.0.1 on 2024-03-08 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0021_ykv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YKV',
            new_name='NightResponsibility',
        ),
    ]
