# Generated by Django 5.0.1 on 2024-03-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0021_merge_20240308_1540'),
        ('ilotalo', '0022_rename_ykv_nightresponsibility'),
    ]

    operations = [
    ]
