# Generated by Django 5.0.1 on 2024-03-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0023_merge_20240311_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(related_name='organizations', to='ilotalo.organization'),
        ),
    ]
