# Generated by Django 5.0.1 on 2024-03-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0025_rename_organizations_user_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ManyToManyField(related_name='organization', to='ilotalo.organization'),
        ),
    ]
