# Generated by Django 5.0.1 on 2024-03-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0026_alter_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keys',
            field=models.JSONField(default=dict),
        ),
    ]
