# Generated by Django 5.0.1 on 2024-04-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0027_user_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='keys',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
