# Generated by Django 5.0.1 on 2024-04-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0028_alter_user_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rights_for_reservation',
            field=models.BooleanField(default=True),
        ),
    ]
