# Generated by Django 5.0.1 on 2024-04-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0030_remove_user_organization_user_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectFault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=300)),
                ('email_sent', models.BooleanField(default=False)),
                ('repaired', models.BooleanField(default=False)),
            ],
        ),
    ]
