# Generated by Django 5.0.1 on 2024-04-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0031_defectfault'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='reservation',
            new_name='organizer',
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
