# Generated by Django 5.0.1 on 2024-05-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0033_nightresponsibility_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightresponsibility',
            name='organisations',
            field=models.ManyToManyField(to='ilotalo.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
