# Generated by Django 5.0.1 on 2024-05-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0034_nightresponsibility_organisations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nightresponsibility',
            name='organisations',
        ),
        migrations.AddField(
            model_name='nightresponsibility',
            name='organisations',
            field=models.CharField(default='', max_length=100),
        ),
    ]
