# Generated by Django 5.0.1 on 2024-05-22 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0035_remove_nightresponsibility_organisations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 22, 7, 41, 13, 469009, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 22, 7, 41, 13, 468991, tzinfo=datetime.timezone.utc)),
        ),
    ]
