# Generated by Django 5.0.1 on 2024-05-22 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0036_alter_event_end_alter_event_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 22, 7, 43, 6, 701538, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 22, 7, 43, 6, 701520, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='nightresponsibility',
            name='login_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 22, 7, 43, 6, 701841, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='nightresponsibility',
            name='logout_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 22, 7, 43, 6, 701850, tzinfo=datetime.timezone.utc)),
        ),
    ]
