# Generated by Django 5.0.1 on 2024-05-22 07:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0037_alter_event_end_alter_event_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='nightresponsibility',
            name='login_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='nightresponsibility',
            name='logout_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
