# Generated by Django 5.0.1 on 2024-05-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilotalo', '0040_alter_event_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
