import axios from "axios";

// 1. Try runtime config from config.js (generated by Docker entrypoint)
// 2. Fallback to build-time process.env.VITE_API_URL
// 3. Fallback to relative path
const API_URL = (window.ENV && window.ENV.API_URL) || process.env.VITE_API_URL || "";

console.log("[DEBUG] window.ENV:", window.ENV);
console.log("[DEBUG] API_URL resolved to:", API_URL || "(relative)");

const axiosClient = axios.create({
  baseURL: `${API_URL}/api`,
});


// Checks the authorization of the user using axios

axiosClient.interceptors.request.use((config) => {
  const token = localStorage.getItem("ACCESS_TOKEN");
  console.log(`[DEBUG] Request: ${config.method.toUpperCase()} ${config.baseURL}${config.url}`);

  if (token && token !== "undefined" && token !== "null") {
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
});

axiosClient.interceptors.response.use(
  (response) => {
    console.log(`[DEBUG] Response from ${response.config.url}:`, response.status, response.data);
    return response;
  },
  (error) => {
    const { response } = error;
    
    if (response) {
      console.error(`[DEBUG] API Error from ${response.config.url}:`, response.status, response.data);
    } else {
      console.error(`[DEBUG] Network/Server Error connecting to ${error.config?.baseURL}${error.config?.url}:`, error.message);
    }

    // If token is invalid or expired (401), clear local storage
    if (response && response.status === 401) {
      localStorage.removeItem("ACCESS_TOKEN");
      localStorage.removeItem("loggedUser");

      // Optional: Redirect to login if not already there
      if (!window.location.pathname.includes('/login')) {
        window.location.href = "/login";
      }
    }

    throw error;
  },
);

export default axiosClient;